package com.projet.safety.safetynet.database_queries;

public class FireStationQueries {

    public static final String SQL_CREATE = "INSERT INTO FIRESTATION(ADDRESS, "
			+"STATION) VALUES (?, ?)";
	
	public static final String SQL_UPDATE = "UPDATE FIRESTATION SET STATION = ? WHERE ADDRESS = ?";
	
	public static final String SQL_DELETE = "DELETE FROM FIRESTATION WHERE ADDRESS = ?";
	
	public static final String SQL_GET_BY_STATION_NUMBER = "SELECT P.FIRST_NAME, P.LAST_NAME, P.ADDRESS, "
			+"P.PHONE FROM PERSON P INNER JOIN FIRESTATION FS ON FS.ADDRESS = P.ADDRESS "
			+ "WHERE FS.STATION = ?";
	
	public static final String SQL_COUNT_ADULTS_CHILDREN = "SELECT SUM(CASE WHEN MR.BIRTHDATE < CURRENT_DATE - INTERVAL '18 YEAR' "
			+ "THEN 1 ELSE 0 END) AS ADULTS, SUM(CASE WHEN MR.BIRTHDATE < CURRENT_DATE - INTERVAL '18 YEAR' "
			+ "THEN 0 ELSE 1 END) AS CHILDREN "
			+ "FROM MEDICALRECORD MR INNER JOIN PERSON P ON P.FIRST_NAME = MR.FIRST_NAME AND P.LAST_NAME = MR.LAST_NAME "
			+ "INNER JOIN FIRESTATION FS ON FS.ADDRESS = P.ADDRESS WHERE FS.STATION = ?";
	
	public static final String SQL_GET_STATION_NUMBER = "SELECT STATION FROM FIRESTATION WHERE ADDRESS = ?";

}
